using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Drawing;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Windows.Forms;

namespace QuickPlot
{
	public partial class DataPlotOptionsForm : Form
	{
		// Private objects
		private DataPlotOptions parentOptions;

		// Public objects
		//reserved

		/// <summary>
		/// Autogenerated class constructor. Not intended for general use
		/// </summary>
		protected DataPlotOptionsForm()
		{
			InitializeComponent();
		}

		/// <summary>
		/// Class constructor taking one input for the parent DataPlotOptions
		/// </summary>
		/// <param name="parent"> Options modified by this form. </param>
		public DataPlotOptionsForm(DataPlotOptions parent)
		{
			parentOptions = parent;

			InitializeComponent();
			colorDropDown.Items.AddRange(new object[] {"Blue",
				"Red"});
			colorDropDown.SelectedIndex = colorDropDown.Items.IndexOf(parentOptions.PlotColorString);
			scalingDropDown.Items.AddRange(Scaling.ScaleOptions.ToArray());
			scalingDropDown.SelectedIndex = Scaling.ScaleOptions.IndexOf(parentOptions.PlotScaling.ScaleMode);
		}

		private void okButton_Click(object sender, EventArgs e)
		{
			parentOptions.PlotColor =
				Color.FromName(colorDropDown.Items[colorDropDown.SelectedIndex].ToString());
			parentOptions.PlotScaling =
				new Scaling(scalingDropDown.Items[scalingDropDown.SelectedIndex].ToString());
			this.Close();
		}

		private void cancelButton_Click(object sender, EventArgs e)
		{
			this.Close();
		}
	}
}
