using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Drawing;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Windows.Forms;

namespace QuickPlot
{
	public partial class FreqPlotOptionsForm : Form
	{
		// Private objects
		private FreqPlotOptions parentOptions;

		// Public objects
		//reserved

		/// <summary>
		/// Autogenerated class constructor. Not intended for general use
		/// </summary>
		protected FreqPlotOptionsForm()
		{
			InitializeComponent();
		}

		/// <summary>
		/// Class constructor taking one input for the parent FreqPlotOptions
		/// </summary>
		/// <param name="parent"> Options modified by this form. </param>
		public FreqPlotOptionsForm(FreqPlotOptions parent)
		{
			parentOptions = parent;

			InitializeComponent();
			waveSelectDropDown.Items.AddRange(Wave.WaveOptions.ToArray());
			waveSelectDropDown.SelectedIndex = Wave.WaveOptions.IndexOf(parentOptions.WaveType.WaveMode);
		}

		private void okButton_Click(object sender, EventArgs e)
		{
			parentOptions.WaveType =
				   new Wave(waveSelectDropDown.Items[waveSelectDropDown.SelectedIndex].ToString());
			this.Close();
		}

		private void cancelButton_Click(object sender, EventArgs e)
		{
			this.Close();
		}
	}
}
